### ISSUE TITLE
Intermittent timing failure in OpenShiftIT

### ISSUE THREAD

**Issue by rdruss** [openshift-vertx-examples/vertx-cache-example-redhat#24]
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 27.345 s <<< FAILURE! - in io.openshift.booster.OpenShiftIT
[ERROR] testCaching(io.openshift.booster.OpenShiftIT)  Time elapsed: 17.526 s  <<< FAILURE!
java.lang.AssertionError: 

Expecting:
 <2635L>
to be less than:
 <2197L> 
	at io.openshift.booster.OpenShiftIT.testCaching(OpenShiftIT.java:112)

Does not always happen, but ...

**Comment by cescoffier** [comment]
Fixed in master

**Comment by cescoffier** [comment]
Community booster also updated.
